export { default as Done } from './Done'
export { default as Close } from './Close'
export { default as Fail } from './Fail'
export { default as Question } from './Question'
export { default as Success } from './Success'
export { default as Warning } from './Warning'